### ISSUE TITLE
feat : timer 코드 변경, TimeConverter 함수명 변경

### ISSUE THREAD

**Issue by suhjaesuk** [DanggeunPlanner/danggeun-planner-BE#64]
## Description
api 변경에 따른 코드 변경

## Todo
- [x] 타이머 시작 시 LocalDateTime.now() 를 받는다.
- [x] 타이머 종료 시 LocalDateTime.now()를 받는다.
- [x] TimeConverter 함수명 변경

## Etc
기타사항
